#security:
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false
logging:
  level:
    fr:
      missfrance: debug
spring:
  thymeleaf:
    content-type: text/html
    suffix: .html
    cache: true
    encoding: UTF-8

  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: test